// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PGManagementSystem.Infrastructure.Data;

#nullable disable

namespace PGManagementSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PGManagementSystem.Domain.Entities.BedMaster", b =>
                {
                    b.Property<Guid>("BedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BedNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("BedRent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TenantName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("char(36)");

                    b.HasKey("BedId");

                    b.HasIndex("ZoneId");

                    b.ToTable("BED_MST");
                });

            modelBuilder.Entity("PGManagementSystem.Domain.Entities.FlatMaster", b =>
                {
                    b.Property<Guid>("FlatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ApartmentName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FlatNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PricingType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("FlatId");

                    b.HasIndex("UserId");

                    b.HasIndex("FlatNumber", "UserId")
                        .IsUnique();

                    b.ToTable("FLAT_MST");
                });

            modelBuilder.Entity("PGManagementSystem.Domain.Entities.NoticeMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByAdminId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("FlatId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SendNotification")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("NOTICE_MST");
                });

            modelBuilder.Entity("PGManagementSystem.Domain.Entities.RentMaster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BaseRent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("BedId")
                        .HasColumnType("char(36)");

                    b.Property<int>("BillingMonth")
                        .HasColumnType("int");

                    b.Property<int>("BillingYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ElectricityBill")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double?>("EndingMeterReading")
                        .HasColumnType("double");

                    b.Property<decimal>("ExtraCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("FlatId")
                        .HasColumnType("char(36)")
                        .HasColumnName("PropertyId");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("LateFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("char(36)");

                    b.Property<double?>("StartingMeterReading")
                        .HasColumnType("double");

                    b.Property<int>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<double?>("UnitsConsumed")
                        .HasColumnType("double");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BedId");

                    b.HasIndex("FlatId");

                    b.HasIndex("RoomId");

                    b.HasIndex("TenantId", "BillingMonth", "BillingYear")
                        .IsUnique();

                    b.ToTable("RENTS_MST");
                });

            modelBuilder.Entity("PGManagementSystem.Domain.Entities.RentPaymentHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PaymentMode")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ReceiptNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<long>("RentId")
                        .HasColumnType("bigint");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RentId");

                    b.ToTable("RENT_PAYMENTS_TRN");
                });

            modelBuilder.Entity("PGManagementSystem.Domain.Entities.RoleMaster", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("ROLE_MST");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "System Administrator with full access",
                            IsActive = true,
                            RoleName = "SuperAdmin"
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "PG Owner / Main Admin",
                            IsActive = true,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "PG Manager / Maintenance Staff",
                            IsActive = true,
                            RoleName = "Staff"
                        },
                        new
                        {
                            RoleId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "PG Tenant / Guest",
                            IsActive = true,
                            RoleName = "Tenant"
                        });
                });

            modelBuilder.Entity("PGManagementSystem.Domain.Entities.TenantMaster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AdvancePaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("AgreementEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("AllocationType")
                        .HasColumnType("int");

                    b.Property<Guid?>("BedId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Deposit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DueDate")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EmergencyPhone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<Guid>("FlatId")
                        .HasColumnType("char(36)")
                        .HasColumnName("PropertyId");

                    b.Property<string>("IdProofNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IdProofType")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("IdProofUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LockInPeriodMonths")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("PoliceVerificationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("Rent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("char(36)");

                    b.Property<double?>("StartingMeterReading")
                        .HasColumnType("double");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TenantPhotoUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("VacatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BedId");

                    b.HasIndex("FlatId");

                    b.HasIndex("RoomId");

                    b.ToTable("TENANTS_MST");
                });

            modelBuilder.Entity("PGManagementSystem.Domain.Entities.UserMaster", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("USER_MST");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("5639d859-f1b8-4a90-bb07-0279f38a580c"),
                            CreatedAt = new DateTime(2026, 8, 5, 17, 55, 4, 367, DateTimeKind.Utc),
                            Email = "patelkrishana006@gmail.com",
                            FullName = "kunal",
                            IsActive = true,
                            PasswordHash = "$2a$11$qBD0lwESQosX0HyV6demwuCbdW1VynMab.SswDPG9nvUOYCJoYGOu",
                            Phone = "6352282175",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("PGManagementSystem.Domain.Entities.ZoneMaster", b =>
                {
                    b.Property<Guid>("ZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<Guid>("FlatId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("RentPerBed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RoomRent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ZoneId");

                    b.HasIndex("FlatId");

                    b.ToTable("ZONE_MST");
                });

            modelBuilder.Entity("PGManagementSystem.Domain.Entities.BedMaster", b =>
                {
                    b.HasOne("PGManagementSystem.Domain.Entities.ZoneMaster", "Zone")
                        .WithMany("Beds")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("PGManagementSystem.Domain.Entities.FlatMaster", b =>
                {
                    b.HasOne("PGManagementSystem.Domain.Entities.UserMaster", "Owner")
                        .WithMany("Flats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PGManagementSystem.Domain.Entities.RentMaster", b =>
                {
                    b.HasOne("PGManagementSystem.Domain.Entities.BedMaster", "Bed")
                        .WithMany()
                        .HasForeignKey("BedId");

                    b.HasOne("PGManagementSystem.Domain.Entities.FlatMaster", "Flat")
                        .WithMany()
                        .HasForeignKey("FlatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PGManagementSystem.Domain.Entities.ZoneMaster", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.HasOne("PGManagementSystem.Domain.Entities.TenantMaster", "Tenant")
                        .WithMany("Rents")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bed");

                    b.Navigation("Flat");

                    b.Navigation("Room");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PGManagementSystem.Domain.Entities.RentPaymentHistory", b =>
                {
                    b.HasOne("PGManagementSystem.Domain.Entities.RentMaster", "Rent")
                        .WithMany("PaymentHistories")
                        .HasForeignKey("RentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rent");
                });

            modelBuilder.Entity("PGManagementSystem.Domain.Entities.TenantMaster", b =>
                {
                    b.HasOne("PGManagementSystem.Domain.Entities.BedMaster", "Bed")
                        .WithMany()
                        .HasForeignKey("BedId");

                    b.HasOne("PGManagementSystem.Domain.Entities.FlatMaster", "Flat")
                        .WithMany()
                        .HasForeignKey("FlatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PGManagementSystem.Domain.Entities.ZoneMaster", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.Navigation("Bed");

                    b.Navigation("Flat");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("PGManagementSystem.Domain.Entities.UserMaster", b =>
                {
                    b.HasOne("PGManagementSystem.Domain.Entities.RoleMaster", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PGManagementSystem.Domain.Entities.ZoneMaster", b =>
                {
                    b.HasOne("PGManagementSystem.Domain.Entities.FlatMaster", "Flat")
                        .WithMany("Zones")
                        .HasForeignKey("FlatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flat");
                });

            modelBuilder.Entity("PGManagementSystem.Domain.Entities.FlatMaster", b =>
                {
                    b.Navigation("Zones");
                });

            modelBuilder.Entity("PGManagementSystem.Domain.Entities.RentMaster", b =>
                {
                    b.Navigation("PaymentHistories");
                });

            modelBuilder.Entity("PGManagementSystem.Domain.Entities.RoleMaster", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PGManagementSystem.Domain.Entities.TenantMaster", b =>
                {
                    b.Navigation("Rents");
                });

            modelBuilder.Entity("PGManagementSystem.Domain.Entities.UserMaster", b =>
                {
                    b.Navigation("Flats");
                });

            modelBuilder.Entity("PGManagementSystem.Domain.Entities.ZoneMaster", b =>
                {
                    b.Navigation("Beds");
                });
#pragma warning restore 612, 618
        }
    }
}
